.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vpub_qt test_vpub_qt
clean: FORCE
	$(MAKE) -C .. vpub_qt_clean test_vpub_qt_clean
check: FORCE
	$(MAKE) -C .. test_vpub_qt_check
bitcoin-qt bitcoin-qt.exe: FORCE
	 $(MAKE) -C .. vpub_qt
